### ISSUE TITLE
ls: ..../certs: No such file or directory

### ISSUE THREAD

**Issue by h1f1x** [sequenceiq/cloudbreak-deployer#106]
Get an error when try to use cbd.
Generating Cloudbreak client certificate and private key does not work.

see the following ....

$ cbd doctor
===> Deployer doctor: Checks your environment, and reports a diagnose.
local version:1.0.1
latest release:1.0.1
boot2docker shellinit: OK
boot2docker date settings: OK
boot2docker: OK
docker command: OK
docker client version: OK
/var/folders/j6/c4v53g3x2gl8rgl3jn4x9nh00019b1/T/bashenv.864811650: line 1588: [: -lt: unary operator expected
docker server version: OK
Generating Cloudbreak client certificate and private key in /data/home/fb/torkspace/cloudbreak-deployer/certs.
ls: /data/home/fb/torkspace/cloudbreak-deployer/certs: No such file or directory

$ uname -a
Darwin myhost 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

**Comment by lalyos** [comment]
hi @h1f1x 

thanks for reporting it. You have probably updated to docker 1.8.x, where they did change, the docker version command output. The issue is fixed already by: #977f42bd74062ea302433c40a7f554076918841f 

until we cut a new version, you can use the latest build from master branch by:
```
cbd update master
```

You can always turn back to the latest official release by:
```
cbd update
```

**Comment by h1f1x** [comment]
Hi @lalyos ,

thanks for the tip. Now I tried again and it still does not work :(

$ DEBUG=1 cbd doctor
	[DEBUG] Use profile: Profile
	[DEBUG] CloudBreak Deployer 1.0.2-master-f27fdac
	===> Deployer doctor: Checks your environment, and reports a diagnose.
	local version:1.0.2-master-f27fdac
	latest release:1.0.2
	[WARN] !!!!!!!!!!!!!!!!!!!!!!!!!!!!
	[WARN] Your version is outdated
	[WARN] !!!!!!!!!!!!!!!!!!!!!!!!!!!!
	[WARN] Please update it by:
	  cbd update
	[DEBUG] checking boot2docker on OSX only ...
	boot2docker shellinit: OK
	[DEBUG] TODO: check for version and instruction for update ...
	boot2docker date settings: OK
	boot2docker: OK
	docker command: OK
	[DEBUG] versionstr=Docker version 1.8.1, build d12ea79
	[DEBUG] fullver=1.8.1
	[DEBUG] numver=181
	docker client version: OK
	[DEBUG] serverVer=1.8.1
	docker server version: OK
	[DEBUG] Consul recursors found on host:  -ecuso 10.0.1.18 -ecuso 10.0.1.9
	[DEBUG] DOCKER_CONSUL_OPTIONS=  -ecuso 10.0.1.18 -ecuso 10.0.1.9
	Generating Cloudbreak client certificate and private key in /data/home/fborchers/torkspace/cloudbreak-deployer/certs.
	ls: /data/home/fborchers/torkspace/cloudbreak-deployer/certs: No such file or directory

here the logfile:

$ cat /tmp/cbd.log
	Client:
	 Version:      1.8.1
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   d12ea79
	 Built:        Thu Aug 13 02:49:29 UTC 2015
	 OS/Arch:      darwin/amd64

	Server:
	 Version:      1.8.1
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   d12ea79
	 Built:        Thu Aug 13 02:49:29 UTC 2015
	 OS/Arch:      linux/amd64

**Comment by lalyos** [comment]
hi @h1f1x 

I see to problems. 
- current working dir.
- sed version

# current working dir

It seems that your current working dir  (`$PWD`) is under `/data/home/fborchers/` . Boot2docker uses VirtualBox's "Guest Addition" to share folders from you mac into the boot2docker vm. It configured to share only `/Users/yourname`.

Please try to move your `cloudbreak-deployer` directory somewhere under `/Users/fborchers`

# sed version

OS X by default comes with an old sed version, and even if you use the latest OS X type sed, its uses nonstandard options. internally we used gnu-sed version 4.2. For short term workaround would you please install gnu-sed:

```
brew install gnu-sed --default-names
```

For mid term solution we will include a correct version of sed with cloudbreak deployer.

**Comment by h1f1x** [comment]
Thanks again @lalyos, for the very good tip and explanation.

The **current working dir** was the problem.
There is still an [open issue](https://github.com/boot2docker/boot2docker/issues/678) in the boot2docker project.But I tried this workaround, and it works for me:

    alias b2dup="boot2docker --vbox-share='/data/users/fborchers=Userhome' up && \
            boot2docker ssh 'sudo mkdir -p /data/users/fborchers && sudo mount -t vboxsf Userhome /data/users/fborchers'"

One final question. Are there any plan to do the switch to  **[Docker Machine](https://docs.docker.com/machine/)**?

**Comment by lalyos** [comment]
hi @h1f1x 

Yes I'm already started to use docker-machine, but run into some corners, where boot2docker and docker-machine behaves deifferently. So yes, we are working on it.

stay tuned ;)
